# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "293f810a998b598dc1cbcc650ba1ca82"
name = "CheckoutLinks"
handle = "oneclickcheckoutlinks"
application_url = "https://phpstack-1035961-5713949.cloudwaysapps.com/"
embedded = true

[webhooks]
api_version = "2024-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://phpstack-1035961-5713949.cloudwaysapps.com/authenticate"
]

[pos]
embedded = false

[build]
