# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "01584217365a2ef71121e7aa927862c2"
name = "Checkout Links"
application_url = "https://abdulrahman.xoarhigh.info/"
embedded = true
handle = "oneclickcheckoutlinks-dev"

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_app_proxy,read_customers,read_inventory,read_locations,read_orders,read_products,write_customers,write_discounts,write_draft_orders,write_orders,write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [ "https://abdulrahman.xoarhigh.info/authenticate" ]

[app_proxy]
url = "/CheckoutLinksProxy"
prefix = "apps"
subpath = "LinkId"

[pos]
embedded = false
